### ISSUE TITLE
Add logging capability 

### ISSUE THREAD

**Issue by l33pf** [l33pf/Crab#13]
Currently lacking a good logging facility for Crab this will help document bugs in the future although at this time is at the back of the development queue for the project. Logging has to take into account the concurrent nature of the crawler (ideally want to use: https://logging.apache.org/log4j/2.x/manual/async.html) and not be a burden on the overall performance.

**Comment by Kartik-Garg** [comment]
Can I get more information about "not be a burden on the overall performance" part?

**Comment by l33pf** [comment]
Sure,

(Apologies for the ambiguity of the statement you highlighted I tend to write issues as a reminder for myself for future tasks, so this is a first !) Ideally what I mean by that is I'd like a logger to not have significant large garbage collection pauses if it can be helped otherwise it will add further latency to the crawl.

This link may explain it better (I have limited knowledge on log4j at the moment): http://www.rationaljava.com/2017/10/allocation-free-logging-with-log4j2.html

**Comment by l33pf** [comment]
This issue has now been resolved following the addition of the logging capability, for more info see commit: **eafe970**
